# Generated by Django 6.0 on 2026-01-06 07:51

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_rtchat', '0004_rename_is_privte_chatgroup_is_private_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmessage',
            name='is_read',
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='group_name',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=128, unique=True),
        ),
    ]
