# Generated by Django 5.2.4 on 2026-01-07 12:41

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_rtchat', '0005_remove_groupmessage_is_read_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgroup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='chatgroup',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='chatgroup',
            name='group_icon',
            field=models.ImageField(blank=True, null=True, upload_to='group_icons/'),
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='group_name',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=128, unique=True),
        ),
    ]
